### ISSUE TITLE
[Asking for dataset annotation]

### ISSUE THREAD

**Issue by NguyenHongDuc2307** [anhtu293/vn_celeb_face_recognition#14]
Thank you for the great work.

I downloaded the dataset of vn_celeb_face in the Google Drive link you shared. 
How there is no annotation. All image files are randomly generated.
Can you please share the annotated data?

**Comment by anhtu293** [comment]
Hi there !

Sorry for the late response, i lost track of notifications from this account.

It's been quite a long time, but I think this is what you need 
- **Training data label**: https://github.com/anhtu293/Vietnamese-Celebrity-Face-Recognition/blob/master/data/train.csv

Also, sorry for the messy code of my studenthood :stuck_out_tongue: . 

If you check for more recent personal toy projects (ex: [nndepth](https://github.com/anhtu293/nndepth), ...) , they are much better organized.

I'm still supporting  [nndepth](https://github.com/anhtu293/nndepth) (more models will be supported this autumn).

Also, 2 other repos are in dev and will be public soon (Implementation of some world models, and visual SLAM (in cpp)).

1 :star: is appriciated :stuck_out_tongue:
